### ISSUE TITLE
Does not respect class names

### ISSUE THREAD

**Issue by CoLdAs1cE** [dmitrijs-balcers/parcel-transformer-ts-css-modules#5]
i use `-` in my names but it changes it to before `-` lowercase and after uppercase
for example:
`grid-item` becomes `gridItem` and then breaks my styling and i have to change my naming to use this :/

**Comment by Poky85** [comment]
Guess this is because of this https://github.com/dmitrijs-balcers/parcel-transformer-ts-css-modules/blob/master/lib/index.js#L4.

**Comment by Poky85** [comment]
@dmitrijs-balcers Would you be open to make your transformer [configurable](https://parceljs.org/plugin-system/authoring-plugins#loading-configuration)? Because I think that configuration of underlying `typed-css-modules` is not concern of Parcel transformer. It would be better if users could configure this themselves.

Also I think it should not set `camelCase: true` by default. Transformer should not care about CSS naming 😄 .

**Comment by Poky85** [comment]
@CoLdAs1cE In the meantime you can

```npm install @poky85/parcel-transformer-ts-css-modules```

**Comment by CoLdAs1cE** [comment]
Nice, will check it out

**Comment by dmitrijs-balcers** [comment]
Thanks guys for reporting this! I will try to look into this.

**Comment by dmitrijs-balcers** [comment]
Please take a look: https://github.com/dmitrijs-balcers/parcel-transformer-ts-css-modules/pull/7
